# Generated by Django 4.0.6 on 2022-07-30 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type_choices',
            field=models.CharField(choices=[('0', 'Admin'), ('1', 'Normal')], default='Normal', max_length=20),
        ),
    ]
